#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Pre-commit Check'
yarn pre-commit ||
(
  echo '🤢🤮🤢🤮 Pre-commit Check Failed 🤢🤮🤢🤮';
  false;
)

# Check tsconfig standards
echo '🏗️👷 tslint Check'
yarn tslint ||
(
  echo '🤡😂❌🤡 Failed TypeScript check. 🤡😂❌🤡
          Are you seriously trying to write that? Make the changes required above.'
  false;
)

# If everything passes... Now we can commit
echo '🤔🤔🤔🤔... Alright... Code looks good to me... Trying to build now. 🤔🤔🤔🤔'

yarn build:dev ||
(
  echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
          Next build failed: View the errors above to see why.
  '
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
